name = "adaptive-auth-engine"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
JWT_SECRET = "dev-secret-key-change-in-production"
TURNSTILE_SECRET = "1x00000000000000000000AA"
ALERT_WEBHOOK = ""
ENVIRONMENT = "development"

# KV namespaces
[[kv_namespaces]]
binding = "SESSIONS"
id = "89091567f28a43449afe6b93ab9816bc"

[[kv_namespaces]]
binding = "METRICS"
id = "f43220bb3724436e9c1a8963b672894b"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "ab328305a3184071907b7572fe28c23e"

[[kv_namespaces]]
binding = "USERS"
id = "7fece0bb027b480084eaf6c062527d14"
